import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'hussein',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'peter',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'headPhone',
      category: 'headPhone',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 11,
      brand: 'exmp',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality headPhone',
    },
    {
      name: 'bag',
      category: 'bag',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'exmp',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality bag',
    },
    {
      name: 'camera',
      category: 'camera',
      image: '/images/p3.jpg',
      price: 420,
      countInStock: 5,
      brand: 'exmp',
      rating: 4.8,
      numReviews: 14,
      description: 'high quality camera',
    },
    {
      name: 'mouse',
      category: 'mouse',
      image: '/images/p4.jpg',
      price: 41,
      countInStock: 15,
      brand: 'exmp',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality mouse',
    },
    {
      name: 'sunglasses',
      category: 'sunglasses',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'exmp',
      rating: 4.5,
      numReviews: 13,
      description: 'high quality sunglasses',
    },
    {
      name: 'Video Game',
      category: 'Video Game',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'exmp',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality Video Game',
    },
  ],
};
export default data;
